name: 💡 功能建议
description: 提交新功能需求或现有功能的改进建议
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        请清晰描述希望实现的功能与实际解决的场景

  - type: textarea
    id: feature_summary
    attributes:
      label: 💡 建议内容
      placeholder: 请清晰简要地描述你希望新增或优化的功能
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 🎯 解决的具体使用场景与痛点
      placeholder: 请详细说明该功能适用的具体场景与预期效果
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 补充说明或参考案例
      placeholder: 可在此处提供界面截图或参考软件案例
    validations:
      required: false
